### PR TITLE
Avoid rarely fatal error when the option is an empty string.

### PR DESCRIPTION
**Pull request by widoz**
Ticket: Possibile php 7.1.x Compatibility issue #10

### CODE REVIEW

**Comment by stevengliebe** [comment]
That looks good. Thank you for this. I will merge both pull requests soon.

Please tell me your WordPress.org username if you want to be added as a contributor.

**Comment by widoz** [comment]
Thank you. Happy to contribute. My wp user is @wido but I don't think I made some of important things. :)

**Comment by wido** [comment]
@widoz You mentioned the wrong person in your PR ;)

**Comment by stevengliebe** [comment]
@wido It was a WordPress.org username. If only GitHub were _that_ smart. ;)

**Comment by widoz** [comment]
Sorry for the inconvenience :)

**Pull request merged**
